### ISSUE TITLE
Notebook solution for get column does not work

### ISSUE THREAD

**Issue by boeddeker** [gertingold/euroscipy16-numpy-tutorial#1]
In https://github.com/gertingold/euroscipy-numpy-tutorial/blob/master/numpy-tutorial-solved.ipynb is Code that should get a column of a matrix (`In [10]:`). The Code there returns a row and is equal to the previous code block (`In [9]`).

```python
In [8]:
matrix = [[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]
Get the second row by slicing twice

In [9]:
matrix[1][:]
Out[9]:
[3, 4, 5]
Try to get the second column by slicing. Do not use a list comprehension!

In [10]:
matrix[:][1]
Out[10]:
[3, 4, 5]
```

**Comment by gertingold** [comment]
Your observation is completely correct. The point of the last input is precisely that lists do not work as one would expect for matrices, thus providing one motivation to use Numpy arrays. I was making this point in the tutorial but I agree that it is not necessarily clear from the notebook.  However, amending the notebook would result in a spoiler when using the notebook in a tutorial session.

May be the issue you have opened together with my response can be useful to others who stumble across this point.

**Comment by boeddeker** [comment]
Ah, ok thanks.
I was a bit confused about how you can get a column without a list comprehension (and without map etc).

**Comment by gertingold** [comment]
And rightly so, because one can't.
